openapi: 3.1.0
info:
  title: Federation Agricole API
  version: 1.0.0
  description: API de gestion des collectivités agricoles à Madagascar

servers:
  - url: http://localhost:8080

paths:

  /collectivites/demandes:
    post:
      summary: Créer une demande d’ouverture de collectivité
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemandeCollectivite'
      responses:
        '201': { description: Demande créée }
        '422': { description: Conditions non respectées }

  /collectivites/demandes/{id}:
    patch:
      summary: Valider ou refuser une demande
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatutDemande'
      responses:
        '200': { description: Statut mis à jour }
        '404': { description: Demande non trouvée }

  /collectivites:
    get:
      summary: Lister les collectivités
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Collectivite' }

    post:
      summary: Créer une collectivité après validation
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Collectivite' }
      responses:
        '201': { description: Créée }
        '403': { description: Demande non validée }

  /collectivites/{id}/admissions:
    post:
      summary: Créer une demande d'admission par un membre
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/DemandeAdmission' }
      responses:
        '201': { description: Demande d'admission créée }
        '400': {description: Données invalides}
        '422': {description: Parrain invalide ou ancienneté insuffisante}

  /admissions/{id}/paiement:
    post:
      summary: Payer les frais d’adhésion
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Paiement'
      responses:
        '200': { description: Paiement effectué }
        '400': {description: Montant incorrect}

  /admissions/{id}/valider:
    post:
      summary: Valider l'admission d'un membre
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '201': {description: Membre officiellement admis}
        '403': {description: Paiement non effectué}
        '404': {description: Demande non trouvée}

  /membres:
    get:
      summary: Liste des membres
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Membre'

  /membres/{id}:
    get:
      summary: Obtenir un membre
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200': { description: OK }
        '404': { description: Non trouvé }

  /membres/{id}/assiduite:
    get:
      summary: Calcul du taux d’assiduité
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
        - in: query
          name: dateDebut
          schema:
            type: string
            format: date
        - in: query
          name: dateFin
          schema:
            type: string
            format: date
      responses:
        '200': { description: Taux calculé }

  /collectivites/{id}/cotisations:
    post:
      summary: Créer une cotisation (payer)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Cotisation' }
      responses:
        '201': { description: Cotisation créée }

  /collectivites/{id}/comptes:
    post:
      summary: Créer un compte
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Compte' }
      responses:
        '201': { description: Compte créé }

    get:
      summary: Liste des comptes
      responses:
        '200': { description: OK }

  /comptes/{id}/solde:
    get:
      summary: Consulter le solde
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200': { description: Solde retourné }

  /collectivites/{id}/activites:
    post:
      summary: Créer une activité
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Activite' }
      responses:
        '201': { description: Activité créée }

    get:
      summary: Liste des activités
      responses:
        '200': { description: OK }

  /activites/{id}/presences:
    post:
      summary: Enregistrer une présence
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Presence' }
      responses:
        '201': { description: Présence enregistrée }

  /collectivites/{id}/statistiques:
    get:
      summary: Statistiques de la collectivité
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Statistiques retournées
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistiques'

components:

  schemas:

    Membre:
      type: object
      properties:
        id:
          type: integer

        nom:
          type: string

        prenom:
          type: string

        dateNaissance:
          type: string
          format: date

        genre:
          type: string
          enum: [ MASCULIN, FEMININ ]

        adresse:
          type: string

        metier:
          type: string

        telephone:
          type: string

        email:
          type: string
          format: email

        dateAdhesion:
          type: string
          format: date

        collectiviteId:
          type: integer

    StatutDemande:
      type: object
      properties:
        statut:
          type: string
          enum: [ APPROUVEE, REFUSEE ]
      required:
        - statut

    DemandeCollectivite:
      type: object
      properties:
        nom: { type: string }
        ville: { type: string }
        specialite: { type: string }
        membresIds:
          type: array
          minItems: 10
          items: { type: integer }

    Collectivite:
      type: object
      properties:
        id: { type: integer }
        nom: { type: string }
        ville: { type: string }
        specialite: { type: string }

    Admission:
      type: object
      properties:
        nom: { type: string }
        prenom: { type: string }
        email: { type: string }
        parrainId: { type: integer }

    Cotisation:
      type: object
      properties:
        montant: { type: number }
        type: { type: string }

    Paiement:
      type: object
      properties:
        montant: { type: number }
        mode: { type: string }

    Compte:
      type: object
      properties:
        type:
          type: string
          enum: [CAISSE, BANCAIRE, MOBILE_MONEY]

    Activite:
      type: object
      properties:
        titre: { type: string }
        date: { type: string, format: date }
        description : {type: string}
        obligatoire: { type: boolean }

    Presence:
      type: object
      properties:
        membreId: { type: integer }
        statut:
          type: string
          enum: [PRESENT, ABSENT, EXCUSE]
        motif:
          type: string
          nullable: true

    DemandeAdmission:
      type: object
      properties:
        nom: { type: string }
        prenom: { type: string }
        email: { type: string }
        telephone: { type: string }
        parrainId: { type: integer }

    Statistiques:
      type: object
      properties:
        nombreMembres:
          type: integer

        tauxAssiduiteGlobal:
          type: number
          format: float

        membres:
          type: array
          items:
            $ref: '#/components/schemas/StatistiqueMembre'

    StatistiqueMembre:
      type: object
      properties:
        membreId:
          type: integer

        tauxAssiduite:
          type: number
          format: float

        montantPaye:
          type: number

        montantImpaye:
          type: number